"""empty message

Revision ID: 02ff4a85293a
Revises: 
Create Date: 2018-12-05 12:17:45.027821

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02ff4a85293a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('graps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('grape_name', sa.String(), nullable=True),
    sa.Column('grape_colour', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('graps')
    # ### end Alembic commands ###
