"""empty message

Revision ID: 217db4f76bc8
Revises: 02ff4a85293a
Create Date: 2018-12-05 13:56:11.202178

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '217db4f76bc8'
down_revision = '02ff4a85293a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('country',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('country_name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('grape',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('grape_name', sa.String(), nullable=True),
    sa.Column('grape_colour', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('region',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('region_name', sa.String(), nullable=True),
    sa.Column('located_in', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['located_in'], ['country.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('wine',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wine_name', sa.String(), nullable=True),
    sa.Column('region_id', sa.Integer(), nullable=True),
    sa.Column('body', sa.String(), nullable=True),
    sa.Column('sweetness', sa.String(), nullable=True),
    sa.Column('typoe', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['region_id'], ['region.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ingredients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('grape_id', sa.Integer(), nullable=True),
    sa.Column('wine_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['grape_id'], ['grape.id'], ),
    sa.ForeignKeyConstraint(['wine_id'], ['wine.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tasting_notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wine_id', sa.Integer(), nullable=True),
    sa.Column('tasting_note', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['wine_id'], ['wine.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('graps')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('graps',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('grape_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('grape_colour', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='graps_pkey')
    )
    op.drop_table('tasting_notes')
    op.drop_table('ingredients')
    op.drop_table('wine')
    op.drop_table('region')
    op.drop_table('grape')
    op.drop_table('country')
    # ### end Alembic commands ###
