"""empty message

Revision ID: a66fbd851890
Revises: 
Create Date: 2019-01-10 15:46:17.687281

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a66fbd851890'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('country',
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('grape',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('colour', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('region',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('country_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['country_id'], ['country.name'], ),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('wine',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('region_id', sa.String(), nullable=True),
    sa.Column('body', sa.String(), nullable=True),
    sa.Column('sweetness', sa.String(), nullable=True),
    sa.Column('wine_type', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['region_id'], ['region.name'], ),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('ingredients',
    sa.Column('ingredients_id', sa.Integer(), nullable=False),
    sa.Column('grape_id', sa.String(), nullable=True),
    sa.Column('wine_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['grape_id'], ['grape.name'], ),
    sa.ForeignKeyConstraint(['wine_id'], ['wine.name'], ),
    sa.PrimaryKeyConstraint('ingredients_id')
    )
    op.create_table('tasting_note',
    sa.Column('tastingnote_id', sa.Integer(), nullable=False),
    sa.Column('wine_id', sa.String(), nullable=True),
    sa.Column('note', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['wine_id'], ['wine.name'], ),
    sa.PrimaryKeyConstraint('tastingnote_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tasting_note')
    op.drop_table('ingredients')
    op.drop_table('wine')
    op.drop_table('region')
    op.drop_table('grape')
    op.drop_table('country')
    # ### end Alembic commands ###
